# Generated by Django 3.1.3 on 2021-02-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210224_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='photo',
        ),
    ]
